analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3535237,"name"\:"Spring Petclinic Test","teamId"\:3540054,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3520273,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3540054,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
