analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3515600,"name"\:"Cellphone Shop Trial \#3515600","teamId"\:3518046,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3517769,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3518046,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
