<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>13ed5e87-f67d-4ec1-8df3-08d2328b5b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-child(4) a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'span') and (position() = 4)]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0791404a-4a0e-4410-9cc6-013ca8369f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/vets.html?page=2</value>
      <webElementGuid>afc29d6c-4f9a-42eb-8490-09b144fe2ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>75b2bda6-27b0-4334-aebf-53c6fd15b1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5327c786bf1db8db83e2510903ca7eec</value>
      <webElementGuid>b56fdbf5-b454-4bfb-8575-dd99f89589c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'span') and (position() = 4)]//a</value>
      <webElementGuid>e6ff2f11-85d2-4841-8e80-0a068a632228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'span') and (position() = 4)]//a</value>
      <webElementGuid>41e15b23-43d5-42bb-b5cc-094dc5eadef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/vets.html?page=2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>d93872bd-8ff8-477b-8416-f8df3eb7818d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
