<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Pet type dropdown on the Add/Edit Pet form.</description>
   <name>select_Type</name>
   <tag></tag>
   <elementGuidId>9add31be-a783-41ea-8008-407b28c25331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af7b60b4-f0bc-413a-9c8a-fedd53e90aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>36d5eec5-284f-4dac-94e1-a1a79e2bdc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>382a3b40-066c-4404-9c8d-b5eeb16c2f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            bird
            cat
            dog
            hamster
            lizard
            snake
          </value>
      <webElementGuid>ce339e83-959c-44dd-a076-4a18917de781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7c28f13c50247cf5c5456092c867f6eb</value>
      <webElementGuid>0a72b38c-3ce3-4402-b1d3-5094a4764a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'type']</value>
      <webElementGuid>de8a5b2f-33dd-4c2a-b7de-1eed0186a4aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'type']</value>
      <webElementGuid>5b09a1d6-c46f-4ede-a7e1-71c5ab152490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'type' and @name = 'type' and (text() = '
            bird
            cat
            dog
            hamster
            lizard
            snake
          ' or . = '
            bird
            cat
            dog
            hamster
            lizard
            snake
          ')]</value>
      <webElementGuid>151b3b4d-88d0-49d8-8179-815dad7e23e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
