<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_span</name>
   <tag></tag>
   <elementGuidId>48dfa7b0-dcd9-4895-aa6b-216a3d143cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-child(9)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'span') and (position() = 9)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span:nth-child(9)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d8ceb7d-514d-405e-b327-1864f8e0ce5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8c6b5f62caa1680c2e4a87ae6d74b2fe</value>
      <webElementGuid>ae919d5c-0135-4ee1-ab39-63001ee57d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'span') and (position() = 9)]</value>
      <webElementGuid>8e76315a-5118-4dc9-95e7-dc69f0adfb06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'span') and (position() = 9)]</value>
      <webElementGuid>1eb7b9e7-23d0-407c-abf9-d01a23b6d0c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
